---
name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: macos-latest
    steps:

    - name: Repo Checkout
      uses: actions/checkout@v3

    - name: Cache Vagrant Boxes
      uses: actions/cache@v3
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('conf/vagrant.yaml') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Check Plugins Installable
      run: vagrant plugin install vagrant-hosts vagrant-cachier vagrant-sshfs 

    - name: Validate Vagrantfile
      run: vagrant validate

